USE MMORPG
GO

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRANSACTION
    SELECT * FROM Players
    SELECT * FROM Players
COMMIT TRANSACTION

-- Solution: Set the isolation level to READ COMMITTED
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRANSACTION
    SELECT * FROM Players
    SELECT * FROM Players
COMMIT TRANSACTION
