USE MMORPG
GO
SELECT @@trancount

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
    SELECT * FROM Players
    SELECT * FROM Players
COMMIT TRANSACTION

-- Solution: Set the isolation level to SERIALIZABLE
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION
    SELECT * FROM Players
    SELECT * FROM Players
COMMIT TRANSACTION
